language: nix

sudo: false

env:
  global:
    - CACHIX_CACHE=yl

matrix:
  include:
    - name: "linux 18.09"
      env: NIXPKGS_CHANNEL=https://nixos.org/channels/nixos-18.09 HM_CHANNEL=https://github.com/rycee/home-manager/archive/release-18.09.tar.gz
      os: linux
    - name: "osx 18.09"
      env: NIXPKGS_CHANNEL=https://nixos.org/channels/nixos-18.09 HM_CHANNEL=https://github.com/rycee/home-manager/archive/release-18.09.tar.gz DARWIN_CHANNEL=https://github.com/LnL7/nix-darwin/archive/master.tar.gz
      os: osx

install:
  - nix-channel --add "${NIXPKGS_CHANNEL}" nixpkgs
  - nix-channel --add "${HM_CHANNEL}" home-manager
  - nix-channel --add "${DARWIN_CHANNEL}" darwin
  - travis_retry nix-channel --update
  - >
    if [ -n "${CACHIX_CACHE}" ]; then
      nix-env -i cachix;
      cachix use "${CACHIX_CACHE}"
    fi
  - >
    if ! echo "${NIX_PATH}" | grep -q "/nix/var/nix/profiles/per-user/$(whoami)/channels"; then
      export NIX_PATH=/nix/var/nix/profiles/per-user/$(whoami)/channels:$NIX_PATH
    fi

before_script:
  - nix --version
  - nix-channel --list

script:
  - >
    if [[ "${TRAVIS_OS_NAME}" == "linux"  ]]; then
      nix build --verbose --show-trace --file ./hosts/cratos/default.nix
      nix build --verbose --show-trace --file ./hosts/hades/default.nix
      nix build --verbose --show-trace --file ./hosts/zeus/default.nix
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      nix build --verbose --show-trace --file ./hosts/athena/default.nix
    else
      echo "OS ${TRAVIS_OS_NAME} is not supported".
      exit 1
    fi
