language: bash
addons:
  apt:
    sources:
      - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
      - shellcheck
before_script:
  - yes 'y' | rake
script:
  - shellcheck -e SC1071 .bin/*
