language: nix

sudo: false

env:
  global:
    - CACHIX_CACHE=yl

matrix:
  include:
    - name: "18.09"
      env: NIXPKGS_CHANNEL=https://nixos.org/channels/nixos-18.09 HM_CHANNEL=https://github.com/rycee/home-manager/archive/release-18.09.tar.gz DARWIN_CHANNEL=https://github.com/LnL7/nix-darwin/archive/master.tar.gz

install:
  - nix-channel --add "${NIXPKGS_CHANNEL}" nixpkgs
  - nix-channel --add "${HM_CHANNEL}" home-manager
  - nix-channel --add "${DARWIN_CHANNEL}" darwin
  - travis_retry nix-channel --update
  - >
    if [ -n "${CACHIX_CACHE}" ]; then
      nix-env -i cachix;
      cachix use "${CACHIX_CACHE}"
    fi

before_script:
  - nix --version
  - nix-channel --list

script:
  - nix build --verbose --show-trace --file ./hosts/athena/default.nix
  - nix-collect-garbage -d
  - nix build --verbose --show-trace --file ./hosts/cratos/default.nix
  - nix-collect-garbage -d
  - nix build --verbose --show-trace --file ./hosts/hades/default.nix
  - nix-collect-garbage -d
  - nix build --verbose --show-trace --file ./hosts/zeus/default.nix

  # Disabled because it requires the private files.
  # TODO: create a shim files to be used just so we can eval & build
  # - nix build --verbose --show-trace --file ./hosts/vpn-nasreddine/default.nix
