language: c
sudo: false
addons:
  apt:
    packages:
    - zsh
before_script:
  - yes 'y' | rake
script:
  - rm "${HOME}/.zshrc"
  - touch "${HOME}/.zshrc"
  - zsh
  - git clone https://github.com/zplug/zplug.git /tmp/zplug && source /tmp/zplug/init.zsh && source ~/.zshrc && zplug install
  - env > /tmp/a
  - yes 'y' | rake
  - source "${HOME}/.zshrc"
  - zplug install
  - source "${HOME}/.zshrc"
  - env > /tmp/b
  - diff -Naur /tmp/a /tmp/b
