language: nix

sudo: false

branches:
  only:
  - master

# env is apparently required!
# See https://docs.travis-ci.com/user/build-matrix/#sts=Rows%20that%20are%20Allowed%20to%20Fail%20#
env:
  global:
    - CACHIX_CACHE=yl

matrix:
  include:
    - name: "athena osx 18.09"
      env: HOST=athena NIXPKGS_CHANNEL=https://nixos.org/channels/nixos-18.09 DARWIN_CHANNEL=https://github.com/LnL7/nix-darwin/archive/master.tar.gz
      os: osx
    - name: "cratos linux 18.09"
      env: HOST=cratos NIXPKGS_CHANNEL=https://nixos.org/channels/nixos-18.09 DARWIN_CHANNEL=https://github.com/LnL7/nix-darwin/archive/master.tar.gz
      os: linux
    - name: "hades linux 18.09"
      env: HOST=hades NIXPKGS_CHANNEL=https://nixos.org/channels/nixos-18.09 DARWIN_CHANNEL=https://github.com/LnL7/nix-darwin/archive/master.tar.gz
      os: linux
    - name: "zeus linux 18.09"
      env: HOST=zeus NIXPKGS_CHANNEL=https://nixos.org/channels/nixos-18.09 DARWIN_CHANNEL=https://github.com/LnL7/nix-darwin/archive/master.tar.gz
      os: linux

  # TODO: add support testing my changes over unstable
  #   - name: "athena osx unstable"
  #     env: HOST=athena NIXPKGS_CHANNEL=https://nixos.org/channels/nixos-unstable DARWIN_CHANNEL=https://github.com/LnL7/nix-darwin/archive/master.tar.gz
  #     os: osx
  #   - name: "cratos linux unstable"
  #     env: HOST=cratos NIXPKGS_CHANNEL=https://nixos.org/channels/nixos-unstable DARWIN_CHANNEL=https://github.com/LnL7/nix-darwin/archive/master.tar.gz
  #     os: linux
  #   - name: "hades linux unstable"
  #     env: HOST=hades NIXPKGS_CHANNEL=https://nixos.org/channels/nixos-unstable DARWIN_CHANNEL=https://github.com/LnL7/nix-darwin/archive/master.tar.gz
  #     os: linux
  #   - name: "zeus linux unstable"
  #     env: HOST=zeus NIXPKGS_CHANNEL=https://nixos.org/channels/nixos-unstable DARWIN_CHANNEL=https://github.com/LnL7/nix-darwin/archive/master.tar.gz
  #     os: linux
  #
  # allow_failures:
  #   - name: "athena osx unstable"
  #     env: HOST=athena NIXPKGS_CHANNEL=https://nixos.org/channels/nixos-unstable DARWIN_CHANNEL=https://github.com/LnL7/nix-darwin/archive/master.tar.gz
  #     os: osx
  #   - name: "cratos linux unstable"
  #     env: HOST=cratos NIXPKGS_CHANNEL=https://nixos.org/channels/nixos-unstable DARWIN_CHANNEL=https://github.com/LnL7/nix-darwin/archive/master.tar.gz
  #     os: linux
  #   - name: "hades linux unstable"
  #     env: HOST=hades NIXPKGS_CHANNEL=https://nixos.org/channels/nixos-unstable DARWIN_CHANNEL=https://github.com/LnL7/nix-darwin/archive/master.tar.gz
  #     os: linux
  #   - name: "zeus linux unstable"
  #     env: HOST=zeus NIXPKGS_CHANNEL=https://nixos.org/channels/nixos-unstable DARWIN_CHANNEL=https://github.com/LnL7/nix-darwin/archive/master.tar.gz
  #     os: linux

install:
  - nix-channel --add "${NIXPKGS_CHANNEL}" nixpkgs
  - nix-channel --add "${DARWIN_CHANNEL}" darwin
  - travis_retry nix-channel --update
  - >
    if [ -n "${CACHIX_CACHE}" ] && [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      nix-env -i cachix;
      cachix use "${CACHIX_CACHE}"
    fi
  - >
    if ! echo "${NIX_PATH}" | grep -q "/nix/var/nix/profiles/per-user/$(whoami)/channels"; then
      export NIX_PATH=/nix/var/nix/profiles/per-user/$(whoami)/channels:$NIX_PATH
    fi

before_script:
  - nix --version
  - nix-channel --list

script:
  # TODO: Building on Travis does not work so for now do eval only and install
  # a dedicated Nix bot on Zeus for the job of the CI.
  #
  # - nix build --verbose --show-trace --file "./hosts/${HOST}"
  - nix-instantiate "./hosts/${HOST}"
