language: c
sudo: false
addons:
  apt:
    packages:
    - zsh
before_script:
  - yes 'y' | rake
script:
  - rm "${HOME}/.zshrc"
  - touch "${HOME}/.zshrc"
  - zsh -i -c "git clone https://github.com/zplug/zplug.git /tmp/zplug && source /tmp/zplug/init.zsh && source ~/.zshrc && zplug install"
  - zsh -i -c "env > /tmp/a"
  - yes 'y' | rake
  - zsh -i -c "zplug install"
  - zsh -i -c "env > /tmp/b"
  - diff -Naur /tmp/a /tmp/b
