var_0: &global_env
  PLACEHOLDER: for_future_use

var_1: &install-nix
  run:
    name: Install Nix
    command: |
      curl https://nixos.org/nix/install | sh

var_2: &install-dependencies
  run:
    name: Install dependencies
    command: |
      if [[ -r "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]]; then
        source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
      fi

      # install git and bash
      nix-env -f '<nixpkgs>' -i -A gitAndTools.git -A bash

      # install cachix from nixpkgs at stable
      readonly shabka_path="$( pwd )"
      release="$( tr -d "\n" < "${shabka_path}/.release" )"
      export NIX_PATH="$( "${shabka_path}/lib/bash/nix-path.sh" "${release}" )"
      nix-env -f '<nixpkgs>' -iA cachix

var_3: &enable-cachix
  run:
    name: Enable cachix
    command: |
      if [[ -r "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]]; then
        source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
      fi

      cachix use "${CACHIX_CACHE}"

var_4: &build-host
  run:
    name: Building the host
    working_directory: ~/shabka
    command: |
      if [[ -r "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]]; then
        source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
      fi

      export DOTSHABKA_PATH="${HOME}/dotshabka"

      ./scripts/build-host.sh "${CIRCLE_JOB}"

var_5: &push-to-cachix
  run:
    name: Push the build to cachix
    working_directory: ~/shabka
    command: |
      if [[ -r "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]]; then
        source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
      fi

      # Cachix is not available for pull requests coming from a fork for security reasons.
      if [[ -z "${CACHIX_SIGNING_KEY:-}" ]]; then
        >&2 echo "CACHIX_SIGNING_KEY is not set, cannot push to cachix"
        exit 0
      fi
      if [[ -z "${CACHIX_CACHE:-}" ]]; then
        >&2 echo "CACHIX_CACHE is not set, cannot push to cachix"
        exit 0
      fi

      export DOTSHABKA_PATH="${HOME}/dotshabka"

      ./scripts/push-to-cachix.sh "${CACHIX_CACHE}" "${CIRCLE_JOB}"

var_6: &download-kalbasit-dotshabka
  run:
    name: Download dotshabka from kalbasit
    working_directory: ~/
    command: |
      if ! git clone https://github.com/kalbasit/dotshabka.git -b "${CIRCLE_BRANCH}"; then
        git clone https://github.com/kalbasit/dotshabka.git
        >&2 echo "Cloned dotshabka from the master branch"
      else
        >&2 echo "Cloned dotshabka from the ${CIRCLE_BRANCH} branch"
      fi

var_7: &download-risson-dotshabka
  run:
    name: Download dotshabka from risson
    working_directory: ~/
    command: |
      if ! git clone https://github.com/rissson/dotshabka.git -b "${CIRCLE_BRANCH}"; then
        git clone https://github.com/rissson/dotshabka.git
        >&2 echo "Cloned dotshabka from the master branch"
      else
        >&2 echo "Cloned dotshabka from the ${CIRCLE_BRANCH} branch"
      fi

version: 2
jobs:
  athena:
    macos:
      xcode: "9.0"

    working_directory: ~/shabka

    environment:
      <<: *global_env

    steps:
      - checkout
      - *install-nix
      - *install-dependencies
      - *enable-cachix
      - *download-kalbasit-dotshabka
      - *build-host
      - *push-to-cachix

  cratos:
    working_directory: ~/shabka

    environment:
      <<: *global_env

    docker:
      - image: nixos/nix

    steps:
      - checkout
      - *install-dependencies
      - *enable-cachix
      - *download-kalbasit-dotshabka
      - *build-host
      - *push-to-cachix

  hades:
    working_directory: ~/shabka

    environment:
      <<: *global_env

    docker:
      - image: nixos/nix

    steps:
      - checkout
      - *install-dependencies
      - *enable-cachix
      - *download-kalbasit-dotshabka
      - *build-host
      - *push-to-cachix

  hera:
    working_directory: ~/shabka

    environment:
      <<: *global_env

    docker:
      - image: nixos/nix

    steps:
      - checkout
      - *install-dependencies
      - *enable-cachix
      - *download-kalbasit-dotshabka
      - *build-host
      - *push-to-cachix

  poseidon:
    macos:
      xcode: "9.0"

    working_directory: ~/shabka

    environment:
      <<: *global_env

    steps:
      - checkout
      - *install-nix
      - *install-dependencies
      - *enable-cachix
      - *download-kalbasit-dotshabka
      - *build-host
      - *push-to-cachix

  zeus:
    working_directory: ~/shabka

    environment:
      <<: *global_env

    docker:
      - image: nixos/nix

    steps:
      - checkout
      - *install-dependencies
      - *enable-cachix
      - *download-kalbasit-dotshabka
      - *build-host
      - *push-to-cachix

  duck:
    working_directory: ~/shabka

    environment:
      <<: *global_env

    docker:
      - image: nixos/nix

    steps:
      - checkout
      - *install-dependencies
      - *enable-cachix
      - *download-risson-dotshabka
      - *build-host
      - *push-to-cachix

  hedgehog:
    working_directory: ~/shabka

    environment:
      <<: *global_env

    docker:
      - image: nixos/nix

    steps:
      - checkout
      - *install-dependencies
      - *enable-cachix
      - *download-risson-dotshabka
      - *build-host
      - *push-to-cachix

workflows:
  version: 2
  testing:
    jobs:
      - athena:
          context: shabka-yl
      - cratos:
          context: shabka-yl
      - hades:
          context: shabka-yl
      - hera:
          context: shabka-yl
      - poseidon:
          context: shabka-yl
      - zeus:
          context: shabka-yl
      - duck:
          context: shabka-risson
      - hedgehog:
          context: shabka-risson
