var_0: &global_env
  CACHIX_CACHE: yl

var_1: &install-nix
  run:
    name: Install Nix
    command: |
      curl https://nixos.org/nix/install | sh

var_2: &install-dependencies
  run:
    name: Install dependencies
    command: |
      if [[ -r "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]]; then
        source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
      fi

      # install git and bash
      nix-env -f '<nixpkgs>' -i -A gitAndTools.git -A bash

      # install cachix from nixpkgs at stable
      readonly shabka_path="$( pwd )"
      release="$( tr -d "\n" < "${shabka_path}/.release" )"
      export NIX_PATH="$( "${shabka_path}/lib/bash/nix-path.sh" "${release}" )"
      nix-env -f '<nixpkgs>' -iA cachix

var_3: &enable-cachix
  run:
    name: Enable cachix
    command: |
      if [[ -r "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]]; then
        source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
      fi

      cachix use "${CACHIX_CACHE}"

var_4: &instantiate-host
  run:
    name: Instantiate the host
    working_directory: ~/shabka
    command: |
      if [[ -r "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]]; then
        source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
      fi

      readonly shabka_path="$( pwd )"
      readonly host="${CIRCLE_JOB}"

      if [[ -r "${shabka_path}/hosts/${host}/release" ]]; then
          release="$( cat "${shabka_path}/hosts/${host}/release" )"
      else
          # fallback to the default release
          release="$( tr -d "\n" < "${shabka_path}/.release" )"
      fi

      export NIX_PATH="$( "${shabka_path}/lib/bash/nix-path.sh" "${release}" )"

      echo ">>> Instantiating the hostname '${host}' using nixpkgs at '${nixpkgs}'. NIX_PATH is set to '${NIX_PATH}'"
      nix-instantiate "${shabka_path}/hosts/${host}"

var_5: &build-host
  run:
    name: Building the host
    working_directory: ~/shabka
    command: |
      if [[ -r "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]]; then
        source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
      fi

      readonly shabka_path="$( pwd )"
      readonly host="${CIRCLE_JOB}"

      if [[ -r "${shabka_path}/hosts/${host}/release" ]]; then
          release="$( cat "${shabka_path}/hosts/${host}/release" )"
      else
          # fallback to the default release
          release="$( tr -d "\n" < "${shabka_path}/.release" )"
      fi

      export NIX_PATH="$( "${shabka_path}/lib/bash/nix-path.sh" "${release}" )"

      echo ">>> Building the hostname '${host}' using nixpkgs at '${nixpkgs}'. NIX_PATH is set to '${NIX_PATH}'"
      nix build -f "${shabka_path}/hosts/${host}"

var_6: &push-to-cachix
  run:
    name: Push the build to cachix
    working_directory: ~/shabka
    command: |
      if [[ -r "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]]; then
        source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
      fi

      readonly shabka_path="$( pwd )"
      readonly host="${CIRCLE_JOB}"

      "${shabka_path}/scripts/push-to-cachix.sh" "${host}"

version: 2
jobs:
  athena:
    macos:
      xcode: "9.0"

    working_directory: ~/shabka

    environment:
      <<: *global_env

    steps:
      - checkout
      - *install-nix
      - *install-dependencies
      - *enable-cachix
      - *instantiate-host

  cratos:
    working_directory: ~/shabka

    environment:
      <<: *global_env

    docker:
      - image: nixos/nix

    steps:
      - checkout
      - *install-dependencies
      - *enable-cachix
      - *build-host
      - *push-to-cachix

  hades:
    working_directory: ~/shabka

    environment:
      <<: *global_env

    docker:
      - image: nixos/nix

    steps:
      - checkout
      - *install-dependencies
      - *enable-cachix
      - *build-host
      - *push-to-cachix

  hera:
    working_directory: ~/shabka

    environment:
      <<: *global_env

    docker:
      - image: nixos/nix

    steps:
      - checkout
      - *install-dependencies
      - *enable-cachix
      - *build-host
      - *push-to-cachix

  poseidon:
    macos:
      xcode: "9.0"

    working_directory: ~/shabka

    environment:
      <<: *global_env

    steps:
      - checkout
      - *install-nix
      - *install-dependencies
      - *enable-cachix
      - *instantiate-host

  zeus:
    working_directory: ~/shabka

    environment:
      <<: *global_env

    docker:
      - image: nixos/nix

    steps:
      - checkout
      - *install-dependencies
      - *enable-cachix
      - *build-host
      - *push-to-cachix

workflows:
  version: 2
  testing:
    jobs:
      - athena:
          context: nix-global
      - cratos:
          context: nix-global
      - hades:
          context: nix-global
      - hera:
          context: nix-global
      - poseidon:
          context: nix-global
      - zeus:
          context: nix-global
